only-pdf load

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,91 +1,63 @@
-name: build and upload latex
+name: upload pdfs to yandex disk
 
 on:
   push:
     branches:
-      - '**'
-      - '!main'
+      - pdf_loader
 
 jobs:
-  prepare:
+  upload:
     runs-on: ubuntu-latest
-    outputs:
-      matrix: ${{ steps.get-targets.outputs.matrix }}
+
     steps:
-      - uses: actions/checkout@v2
-  
-      - name: Get targets
-        id: get-targets
+      - uses: actions/checkout@v3
+
+      - name: Find pdf files
+        id: files
         run: |
-          export BRANCH=${GITHUB_REF#refs/heads/}
-          python -c '
-          import json
-          import os
-          targets = json.load(open("config.json", "r"))[os.environ["BRANCH"]]
-          print("::set-output name=matrix::[", ", ".join(repr(t) for t in targets if not t.startswith("!")), "]", sep="")
-          '
+          FILES=$(find pdf -name "*.pdf" | sed 's|^pdf/||')
+          printf "%s\n" "$FILES"
+          echo "files<<EOF" >> $GITHUB_OUTPUT
+          printf "%s\n" "$FILES" >> $GITHUB_OUTPUT
+          echo "EOF" >> $GITHUB_OUTPUT
 
-  build:
-    needs: prepare
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        course: ${{ fromJson(needs.prepare.outputs.matrix) }}
-    steps:
-      - uses: actions/checkout@v2
-      
-      - name: Configure build
-        id: configure-build
+      - name: Upload to Yandex Disk
         run: |
-          pwd
-          mkdir build
-          BRANCH_NAME=${{ matrix.course }}
-          echo "BRANCH_NAME=$(echo ${BRANCH_NAME})" >> $GITHUB_ENV
-          BRANCH_ARGUMENTS=(${BRANCH_NAME//\// })
-          
-          TYPE=${BRANCH_ARGUMENTS[0]}
-          SEMESTER=${BRANCH_ARGUMENTS[1]}
-          SUBJECT_NAME=${BRANCH_ARGUMENTS[2]}
-          CONSPECT_NAME=${BRANCH_ARGUMENTS[3]}
-          
-          case ${TYPE} in
-            l)
-              TYPE="Lectures"
-              ;;
-            s)
-              TYPE="Seminars"
-              ;;
-            e)
-              TYPE="Exams"
-              ;;
-            *)
-              TYPE="Other"
-              ;;
-          esac
-          SEMESTER="${SEMESTER}_Semester"
+          while read FILE; do
 
-          FULL_PATH="${TYPE}/${SEMESTER}/${SUBJECT_NAME}/${CONSPECT_NAME}"
-          echo "FULL_PATH=$(echo ${FULL_PATH})" >> ${GITHUB_ENV}
+            TYPE=$(echo $FILE | cut -d/ -f1)
+            SEM=$(echo $FILE | cut -d/ -f2)
+            SUBJECT=$(echo $FILE | cut -d/ -f3)
+            NAME=$(basename "$FILE" .pdf)
 
-      - name: Build
-        id: build
-        uses: xu-cheng/latex-action@v2
-        with:
-          root_file: main.tex
-          working_directory: ${{ env.FULL_PATH }}
-          args: -output-dir=../../../../build
-          compiler: pdflatex
-          post_compile: "pdflatex -output-dir=${GITHUB_WORKSPACE}/build main.tex"
+            case $TYPE in
+              l) TYPE="Lectures" ;;
+              s) TYPE="Seminars" ;;
+              e) TYPE="Exams" ;;
+              *) TYPE="Other" ;;
+            esac
 
-      - name: Upload
-        id: upload
-        run: |
-          URL=$(curl -f --silent --get \
-          --data-urlencode 'path=Lectures Tex Club/${{ env.FULL_PATH }}.pdf' \
-          --data-urlencode 'overwrite=true' \
-          --header 'Authorization: ${{ secrets.YANDEX_OAUTH_TOKEN }}' \
-          'https://cloud-api.yandex.net/v1/disk/resources/upload' | jq -r '.["href"]')
+            SEM="${SEM}_Semester"
 
-          curl -f --silent -X PUT --data-binary '@build/main.pdf' \
-          --header 'Authorization: ${{ secrets.YANDEX_OAUTH_TOKEN }}' ${URL}
+            REMOTE_PATH="Lectures Tex Club/${TYPE}/${SEM}/${SUBJECT}/${NAME}.pdf"
+
+            echo "Uploading $FILE -> $REMOTE_PATH"
+
+            URL=$(curl -s --get \
+              --data-urlencode "path=$REMOTE_PATH" \
+              --data-urlencode "overwrite=true" \
+              --header "Authorization: ${{ secrets.YANDEX_OAUTH_TOKEN }}" \
+              https://cloud-api.yandex.net/v1/disk/resources/upload \
+              | jq -r '.href')
+
+            if [ -z "$URL" ] || [ "$URL" = "null" ]; then
+              echo "Failed to get upload URL for $FILE"
+              exit 1
+            fi
+
+            curl -s -X PUT \
+              --data-binary "@pdf/$FILE" \
+              --header "Authorization: ${{ secrets.YANDEX_OAUTH_TOKEN }}" \
+              "$URL"
+
+          done <<< "${{ steps.files.outputs.files }}"
